In [3]:
#2.3.3 Numerical Python
import numpy as np

In [4]:
x = np.array([3, 4, 5])
y = np.array([1, 2, 3])
x + y

array([4, 6, 8])

In [5]:
z = np.array([[2,3,4], [1,2,6], [0,2,1]])
print(z)
z.ndim

[[2 3 4]
 [1 2 6]
 [0 2 1]]


2

In [7]:
z.shape

(3, 3)

In [9]:
print(z.sum())
np.sum(z)

21


21